version: '3'

services:
        snake-io:
                build:
                        .
                container_name: snake-io
                restart: unless-stopped
                ports:
                        - 80:8080

